name: Auto-Merge Codex Updates

on:
  push:
    branches:
      - 'codex/**'   # alle Codex-Branches triggern diesen Workflow

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Configure merge driver
        run: git config merge.theirs.driver true

      - name: Merge Codex branch into main
        run: |
          git fetch origin +${{ github.ref }}:${{ github.ref }}
          git merge -X theirs ${{ github.r
