name: Update lineups dataset

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'

jobs:
  build-lineups:
    name: Refresh lineup dataset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate lineup dataset
        run: python scripts/update_lineups.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: update lineup dataset'
          title: 'chore: update lineup dataset'
          body: 'Automated update of lineup dataset.'
          branch: automation/update-lineups
          add-paths: |
            docs/data/aufstellungen.json
