name: Update scouting statistics overviews

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: write

jobs:
  build-usc-stats-overview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python Scouting/scripts/update_usc_stats_overview.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data/usc_stats_overview.json docs/data/hamburg_stats_overview.json
          git commit -m "chore: update scouting statistics overviews" || echo "No changes"
          git push
